# Generated by Django 4.2.11 on 2025-11-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_remove_stocktransaction_related_transaction_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="storestock",
            options={
                "verbose_name": "Store Stock",
                "verbose_name_plural": "Store Stocks",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="fixed_price",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="is_taxable",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="tax_rate",
            field=models.DecimalField(decimal_places=2, default=16.0, max_digits=5),
        ),
    ]
