# Generated by Django 4.2.11 on 2025-12-02 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_alter_category_options_category_created_by_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stocktransaction",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="transfer_to_store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="incoming_transactions",
                to="inventory.store",
            ),
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outgoing_transactions",
                to="inventory.store",
            ),
        ),
    ]
