# Generated by Django 4.2.11 on 2025-12-02 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
        ("inventory", "0005_alter_stocktransaction_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stocktransfer",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="stocktransfer",
            name="approved_by",
        ),
        migrations.AddField(
            model_name="stocktransfer",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="stocktransfer",
            name="performed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_transfers",
                to="account.user",
            ),
        ),
        migrations.AddField(
            model_name="stocktransfer",
            name="status",
            field=models.CharField(default="completed", editable=False, max_length=20),
        ),
    ]
