# Generated by Django 4.2.11 on 2025-12-04 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_alter_stocktransfer_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BulkRestock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("include_all", models.BooleanField(default=False)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.category",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulk_restocks",
                        to="inventory.store",
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at"],
            },
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("IN", "Stock In"),
                    ("OUT", "Stock Out"),
                    ("TRANSFER_OUT", "Transfer Out"),
                    ("TRANSFER_IN", "Transfer In"),
                ],
                max_length=13,
            ),
        ),
        migrations.CreateModel(
            name="BulkRestockItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_quantity", models.PositiveIntegerField()),
                ("new_quantity", models.PositiveIntegerField()),
                ("current_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "new_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.product",
                    ),
                ),
                (
                    "restock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inventory.bulkrestock",
                    ),
                ),
            ],
            options={
                "unique_together": {("restock", "product")},
            },
        ),
    ]
