# Generated by Django 6.0.4 on 2026-05-09 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_bulkrestock_completed_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocktransaction",
            name="new_quantity",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="previous_quantity",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
