# Generated by Django 6.0.4 on 2026-05-09 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_stocktransaction_new_quantity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stocktransfer",
            name="status",
        ),
        migrations.AddField(
            model_name="stocktransfer",
            name="transfer_code",
            field=models.CharField(
                blank=True, editable=False, max_length=11, null=True, unique=True
            ),
        ),
    ]
