# Generated by Django 6.0.4 on 2026-05-09 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_remove_stocktransfer_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocktransfer",
            name="status",
            field=models.CharField(default="completed", editable=False, max_length=20),
        ),
    ]
