# Generated by Django 6.0.4 on 2026-05-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_stocktransfer_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="bulkrestock",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("editing", "Editing"),
                    ("reviewed", "Reviewed"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
