# Generated by Django 4.2.11 on 2025-12-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "account",
            "0003_remove_user_password_hash_user_groups_user_password_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("cashier", "Cashier"),
                    ("manager", "Manager"),
                ],
                default="cashier",
                max_length=20,
            ),
        ),
    ]
