# Generated by Django 4.2.11 on 2025-12-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_rename_created_at_user_date_joined_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AddField(
            model_name="user",
            name="pin",
            field=models.CharField(default="0000", max_length=4, unique=True),
            preserve_default=False,
        ),
    ]
