# Generated by Django 4.2.11 on 2025-12-10 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_remove_user_username_user_pin"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="pin",
            new_name="unique_id",
        ),
    ]
