# Generated by Django 4.2.11 on 2026-04-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_rename_pin_user_unique_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="unique_id",
            field=models.CharField(editable=False, max_length=4, unique=True),
        ),
    ]
