# Generated by Django 6.0.4 on 2026-05-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0008_alter_user_unique_id"),
        (
            "inventory",
            "0007_bulkrestock_alter_stocktransaction_transaction_type_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="stores",
            field=models.ManyToManyField(blank=True, to="inventory.store"),
        ),
    ]
